// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehmtkujwcrpactubddpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobXRrdWp3Y3JwYWN0dWJkZHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTE0OTMsImV4cCI6MjA2NjQ2NzQ5M30.UGF8jIG8z1SiNSvWP1mit5pk3Td6UADIh1hfKy5-rts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);